### ISSUE TITLE
Prefectch plugin issue

### ISSUE THREAD

**Issue by ghost** [forensicxlab/volatility3_plugins#1]
```
$ vol -f dump.mem prefetch
Volatility 3 Framework 2.4.1
Progress:  100.00               Stacking attempts finished
Unsatisfied requirement plugins.Prefetch.kernel.layer_name:
Unsatisfied requirement plugins.Prefetch.kernel.symbol_table_name:

A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The file is a valid memory image and was acquired cleanly

A symbol table requirement was not fulfilled.  Please verify that:
        The associated translation layer requirement was fulfilled
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Prefetch.kernel.layer_name', 'plugins.Prefetch.kernel.symbol_table_name']
```

How to fix it?

**Comment by forensicxlab** [comment]
Hello n00bth3b0x, 
The symbol table for your memory dump was not found. The issue here doesn't seems to be linked to the prefetch plugin. If Windows symbols that cannot be found will be queried, downloaded, generated and cached

Please make sure : 
- That the memory dump you have comes from a Windows system. 
- That the machine you are using to conduct your investigation is connected to the internet so volatility can fetch the symbol tables.

If you are using and air gapped machine, symbol tables must be manually produced by a tool such as [dwarf2json](https://github.com/volatilityfoundation/dwarf2json) then specified to the volatility3 framework using the "-s" option.

Learn more here : https://volatility3.readthedocs.io/en/stable/basics.html#symbol-tables

Best regards.
Félix.

**Comment by ghost** [comment]
I can use all plugin but yours, that's the issue

**Comment by forensicxlab** [comment]
> I can use all plugin but yours, that's the issue

Hello @n00bth3b0x, 
That is unfortunate. Could you run the framework using this command :  `vol -vvvvv -f dump.mem windows.prefetch` then paste the result in this issue so I can help ?

FWI, I have made a pull request to the official volatility3 repository for the inclusion of the prefetch decompression algorithm.  If included, I will make a pull request to include this prefetch plugin and the others in time so It can be present in the framework natively.

Best regards.
Félix.
